services:
  couchdb:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=test
    volumes:
        - ./data:/opt/couchdb/data
        - ./config/memoria.ini:/opt/couchdb/etc/local.ini
